slack_settings:
  channel: slack-channel-name
  username: slack-user-name
  icon_emoji: icon-for-chat
  url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
sites:
  settings:
      env: dev
      report: false
      upstream: true
      auto-commit: true
      skip-backup: true
      auto-deploy: true
  update:
    - name: test-site-1
    - name: test-site-2
    - name: test-site-3
