slack_settings:
  username: slack-user-name
  icon_emoji: icon-for-chat
  url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
  notifications:
    updated:
      - user-slack-1
      - user-slack-2
sites:
  settings:
      env: dev
      upstream: true
      update: true
      auto_commit: true
      backup: true
      auto_deploy: true
      exclude:
        - plugin-name
      major_update: false
  update:
    - name: test-site-1
      notifications:
        report:
          - user-slack-3
        updated:
          - user-slack-3
          - user-slack-4
    - name: test-site-2
    - name: test-site-3
      notifications:
        error:
          - user-slack-5
          - user-slack-6